### PR TITLE
Update gorm unique index tag as per latest gorm

### PR DESCRIPTION
**Pull request by agbaraka**
Reference: https://gorm.io/docs/indexes.html#uniqueIndex

### CODE REVIEW

**Review by System-Glitch — APPROVED** [review]
Good catch, I wasn't aware of this change. Is it a change from Gorm 2.0 or did it come later?

Thank you  for the PR!

**Comment by agbaraka** [comment]
> Good catch, I wasn't aware of this change. Is it a change from Gorm 2.0 or did it come later?
> 
> 
> 
> Thank you  for the PR!

I think it's a change from Gorm 2.0. They seem to change all tags configs from snake_case to camelCase.

**Comment by System-Glitch** [comment]
I think snake case still works but I'd have to check it out just to be sure.

**Comment by System-Glitch** [comment]
I found the commit, it is a breaking change from the latest patch version of gorm (v1.20.8). I opened an issue: https://github.com/go-gorm/gorm/issues/3846

**Pull request merged**
